# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - TYPE=mysql DSN=mysql://root@localhost/spot_test
  - TYPE=pgsql DSN=pgsql://postgres@localhost/spot_test"
  - TYPE=sqlite DSN=sqlite::memory

install:
  - composer install

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - if [[ "$TYPE" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS spot_test;" -uroot; fi
  - if [[ "$TYPE" == "pgsql" ]]; then psql -c 'create database spot_test;' -U postgres; fi

# omitting "script:" will default to phpunit
# use the $TYPE env variable to determine the phpunit.xml to use
script: phpunit --configuration phpunit_$TYPE.xml --coverage-text
